# Generated by Django 5.2.1 on 2025-05-16 09:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g., Summer Sale, Clearance', max_length=255)),
                ('discount_percentage', models.DecimalField(decimal_places=2, help_text='Percentage discount (e.g., 10.00 for 10% off)', max_digits=5)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discounts', to='products.product')),
            ],
            options={
                'ordering': ['-start_date', '-discount_percentage'],
            },
        ),
    ]
